### PR TITLE
guards against null returned from getClassModel()

### PR DESCRIPTION
**Pull request by samunders-core**
I got hit by NPEs when attempting right-click decompiled function argument > 'Auto Fill in Class Structure', I assume due to unknown parent hierarchies. Left 1 // FIXME as I honestly don't know what should be appropriate there.

Thanks & take care, sam_

### CODE REVIEW

**Comment by astrelsky** [comment]
I'll have to look into this further as it should be impossible. Either the __vmi_class_type_info in question is invalid or it's base type is dynamic and not being handled correctly.

May you tell me more about the class in question this occurs with?

**Comment by samunders-core** [comment]
Well, that might be impossible to answer as I moved on with my workflow and I'm unable to recall exact context I was in when it happened. I have added logging of null returns but so far I'm unable to trigger it.

**Comment by astrelsky** [comment]
> Well, that might be impossible to answer as I moved on with my workflow and I'm unable to recall exact context I was in when it happened. I have added logging of null returns but so far I'm unable to trigger it.

No problem. I think it is more appropriate to instead handle the situation where the __base_class_type_info is invalid for some reason. This should never occur but there may be some edge case that I'm not currently aware of yet.

**Comment by samunders-core** [comment]
OK, I managed to log something. Not exactly the use-case I was describing in original report, but null returned by getClassModel() it is. Actions tried are just Analysis > One Shot > GCC RTTI Analyzer. Log says: (VmiClassTypeInfoModel) getInheritableVirtualParents(): null getClassModel() at 0x00ec6940.
1_npe_related to_0x00ec6940
2_npe_related_to_0x00ec6940
3_npe_related_to_0x00ec6940
I assume its caused by DAT_4778bcd5 not being in memory. For the time being I don't have corresponding .so file + its load address so I cannot try whether it would fix the NPE without this MR.

BR, sam_

**Comment by astrelsky** [comment]
Hmm. Did the symbol for `__si_class_type_info::vtable` come from debug info? Then this is definitely an edge case I've never seen before. May you show what the data looks like at `__vmi_class_type_info::vtable`?

**Comment by samunders-core** [comment]
> Hmm. Did the symbol for `__si_class_type_info::vtable` come from debug info? Then this is definitely an edge case I've never seen before. May you show what the data looks like at `__vmi_class_type_info::vtable`?
> 
```
$ file *redacted*

*redacted*: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.1.1, BuildID[sha1]=212812cdbe563f5fc849cc57ee799f074191ba33, stripped
```
I'd say it's not from debug info
> What is strange is that if the functions in the `__si_class_type_info::vtable` aren't in memory, then I would also expect the vtable to not be in memory either.
> 
> Is `__si_class_type_info::type_info` in memory? 0x477ee708 _should_ be the address according to that vtable but it may not be. I'm finding this to be suspicious as I cannot think of a logical reason for a compiler to do this. However, looking at the other data the `__si_class_type_info::vtable` really should be correct.
> 
```
$ cat /proc/$PID/maps
...
47740000-477dd000 r-xp 00000000 fd:00 179        /lib/libstdc++.so.6.0.20
477dd000-477ed000 ---p 0009d000 fd:00 179        /lib/libstdc++.so.6.0.20
477ed000-477f0000 r--p 0009d000 fd:00 179        /lib/libstdc++.so.6.0.20
477f0000-477f2000 rw-p 000a0000 fd:00 179        /lib/libstdc++.so.6.0.20
...
```
I have used https://gist.github.com/samunders-core/278ff7f7298811d962dfed57cfd44393 to import all .so libraries and no more NPEs were thrown, thus this report is caused by me importing only main executable, without dynamic libraries. I understand this is my error, but I would expect Ghidra-Cpp-Class-Analyzer to be more robust. Instead of popup dialogs log those NPEs/suggest .so needs to be added to program memory (if just preventing them as in this PR is not enough) 

> I may end up accepting the request as it may be an edge case I cannot solve. Unfortunately it will likely have a large impact on the analysis quality because a large majority of the rtti will be affected. It has definitely peaked my interest though.
> 
I'm sorry I don't follow here, anyway feel free to close this PR. Thanks again for your time&support, sam_

**Comment by astrelsky** [comment]
Oh. There is a regression somewhere. I have a specific exception that is thrown when the external data isn't available. It should have thrown that which gets caught, logged and reported when analysis completes. I'll have to come up with a regression test specifically for this.

**Pull request closed without merging**
